version: '2'

networks:
  net_basic:

services:

  orderer.healthcare.kr:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.healthcare.kr
    container_name: orderer.healthcare.kr
    networks:
      - net_basic

  peer0.Hospitals.healthcare.kr:
    container_name: peer0.Hospitals.healthcare.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.Hospitals.healthcare.kr
    networks:
      - net_basic

  peer0.Patients.healthcare.kr:
    container_name: peer0.Patients.healthcare.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.Patients.healthcare.kr
    networks:
      - net_basic

  peer0.Labs.healthcare.kr:
    container_name: peer0.Labs.healthcare.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.Labs.healthcare.kr
    networks:
      - net_basic

  peer0.InsuranceCompanies.healthcare.kr:
    container_name: peer0.InsuranceCompanies.healthcare.kr
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.InsuranceCompanies.healthcare.kr
    networks: 
      - net_basic

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.Hospitals.healthcare.kr:7051
      - CORE_PEER_LOCALMSPID=HospitalsMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Hospitals.healthcare.kr/peers/peer0.Hospitals.healthcare.kr/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Hospitals.healthcare.kr/peers/peer0.Hospitals.healthcare.kr/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Hospitals.healthcare.kr/peers/peer0.Hospitals.healthcare.kr/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Hospitals.healthcare.kr/users/Admin@Hospitals.healthcare.kr/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincode/:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.healthcare.kr
      - peer0.Hospitals.healthcare.kr
      - peer0.Patients.healthcare.kr
      - peer0.Labs.healthcare.kr
      - peer0.InsuranceCompanies.healthcare.kr
    networks:
      - net_basic
